# Default Profile
spring.application.name=Todo Application

# Active Profile (change to 'prod' for production)
spring.profiles.active=dev

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.todo=DEBUG
